#!/bin/bash

echo "$1"
if [ "$1" = "normal" ]
    then
        xinput set-prop 'SynPS/2 Synaptics TouchPad' 'Coordinate Transformation Matrix' 1 0 0 0 1 0 0 0 1 
elif [ "$1" = "left" ]
    then
        xinput set-prop 'SynPS/2 Synaptics TouchPad' 'Coordinate Transformation Matrix' 0 -1 1 1 0 0 0 0 1 
elif [ "$1" = "right" ]
    then
        xinput set-prop 'SynPS/2 Synaptics TouchPad' 'Coordinate Transformation Matrix' 0 1 0 -1 0 1 0 0 1 
else
    xinput list-props 'SynPS/2 Synaptics TouchPad' | grep "Coordinate Transformation Matrix"
fi
